/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface OneTouchButton {
        "label": string;
        "variant": string;
    }
    interface OneTouchInput {
        "align": string;
        "label": string;
        "type": string;
    }
}
export interface OneTouchButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOneTouchButtonElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLOneTouchButtonElement extends Components.OneTouchButton, HTMLStencilElement {
    }
    var HTMLOneTouchButtonElement: {
        prototype: HTMLOneTouchButtonElement;
        new (): HTMLOneTouchButtonElement;
    };
    interface HTMLOneTouchInputElement extends Components.OneTouchInput, HTMLStencilElement {
    }
    var HTMLOneTouchInputElement: {
        prototype: HTMLOneTouchInputElement;
        new (): HTMLOneTouchInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "one-touch-button": HTMLOneTouchButtonElement;
        "one-touch-input": HTMLOneTouchInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface OneTouchButton {
        "label"?: string;
        "onBtnClick"?: (event: OneTouchButtonCustomEvent<any>) => void;
        "variant"?: string;
    }
    interface OneTouchInput {
        "align"?: string;
        "label"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "one-touch-button": OneTouchButton;
        "one-touch-input": OneTouchInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "one-touch-button": LocalJSX.OneTouchButton & JSXBase.HTMLAttributes<HTMLOneTouchButtonElement>;
            "one-touch-input": LocalJSX.OneTouchInput & JSXBase.HTMLAttributes<HTMLOneTouchInputElement>;
        }
    }
}
